___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [4]:
np.__version__


'1.20.3'

Створити вектор з 10 елементів, заповнений одиницями:

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [9]:
np.reshape(np.zeros(5*5), (5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [63]:
vec = np.random.random(20)
print("Вектор з 20 випадковими числами:")
print(vec)
print("Індекси ненульових значень:")
print(np.nonzero(vec))

Вектор з 20 випадковими числами:
[0.08851606 0.87822778 0.65774661 0.43465601 0.48918228 0.89903795
 0.85227257 0.82947205 0.23151906 0.99274698 0.79620621 0.11175927
 0.90398451 0.47470716 0.16339846 0.94993968 0.86249208 0.69812272
 0.68765752 0.95103055]
Індекси ненульових значень:
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [65]:
print("Середнє: ",np.mean(vec))
print("Медіана: ",np.median(vec))
print("Стандартне відхилення: ",np.average(vec))

Середнє:  0.6476337754083239
Медіана:  0.7471644651077658
Стандартне відхилення:  0.6476337754083239


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [96]:
a = np.reshape(np.random.random(4*2),(4,2))*4
b = np.reshape(np.random.random(2*2),(2,2))*8
a = np.dot(a,b)
print(a)

[[13.5885479  18.20041414]
 [12.89267335 15.20206977]
 [ 1.61047169 12.26429622]
 [14.66207632 12.98277069]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [97]:
min_a = np.amin(np.reshape(a, (1,-1)))
max_a = np.amax(np.reshape(a, (1,-1)))
c = a
c[c==min_a] = 0
print("Мінімум: ",min_a,"Максимум: ",max_a)
print("Фінальна матриця: ")
print(c)

Мінімум:  1.6104716893854927 Максимум:  18.20041414033365
Фінальна матриця: 
[[13.5885479  18.20041414]
 [12.89267335 15.20206977]
 [ 0.         12.26429622]
 [14.66207632 12.98277069]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [98]:
val = np.vstack((a[0],a[1:]))
corr = np.corrcoef(val)
print("Кореляція: ")
print(corr)

Кореляція: 
[[ 1.  1.  1. -1.]
 [ 1.  1.  1. -1.]
 [ 1.  1.  1. -1.]
 [-1. -1. -1.  1.]]


Дано матрицю. Знайти ранг матриці:

In [100]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
rank = np.linalg.matrix_rank(a)
print("Ранк матриці: ",rank)

Ранк матриці:  3


Знайти визначник матриці:

In [77]:
det = np.linalg.det(a)
print("Визначник: ",det)

Визначник:  440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [106]:
print("Власні вектори матриці: ")
print(np.linalg.eig(a)[0])
print("Власні значення матриці: ")
print(np.linalg.eig(a)[1])

Власні вектори матриці: 
[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні значення матриці: 
[[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [95]:
from scipy import stats
a = np.random.randint(0,10,50)
print("Найчастіше значення: ",stats.mode(a)[0])

Найчастіше значення:  [8]


Виведіть лише парні числа, що діляться на 5:

In [126]:
a = np.random.randint(0,10,50)
print(a[np.where(a%10 == 0)])

[0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [125]:
x1 = np.array([[2., 5.], [1., -10.]])
x2 = np.array([1., 3.])
sqrs = np.linalg.solve(x1,x2)
print(sqrs)

[ 1.  -0.2]
